TOPIC_BANK = [
    ("Lunch Table Stories", "What was the funniest moment at lunch this week?"),
    ("Group Project Wins", "What makes a school group work well together?"),
    ("Friendship Signals", "How can you tell when someone is a good friend?"),
    ("After-School Plans", "How do you like to spend time after school?"),
    ("Study Habits", "Which study habit helps you remember things best?"),
    ("Classroom Courage", "When did you feel brave enough to speak in class?"),
    ("Weekend Discoveries", "What did you discover or try last weekend?"),
    ("Music on Repeat", "Which song matches your mood today, and why?"),
    ("Books and Characters", "Which character would make a great classmate?"),
    ("Games We Share", "What game is more fun when friends play together?"),
    ("Creative Hobbies", "What do you enjoy creating in your free time?"),
    ("Sports and Teamwork", "What can a team do after making a mistake?"),
    ("Hong Kong Adventures", "Where would you take a new friend in Hong Kong?"),
    ("Dream School Trip", "Where should your class go for a school trip?"),
    ("Travel Surprises", "What can make a family trip especially memorable?"),
    ("Food with Friends", "Which food would you introduce to an overseas friend?"),
    ("Helpful Technology", "Which app makes school life easier for students?"),
    ("Online Kindness", "How can students make group chats more friendly?"),
    ("Planet-Friendly School", "What could your school do to create less waste?"),
    ("Future Careers", "What kind of work might feel meaningful to you?"),
    ("School Celebrations", "Which school event brings students together best?"),
    ("Learning from Mistakes", "What useful lesson came from a recent mistake?"),
    ("Personal Style", "How can clothes help someone express their personality?"),
    ("Healthy Routines", "Which small routine gives you more energy each day?"),
    ("Movie Discussions", "Which movie ending would you like to change?"),
    ("New Student Welcome", "How would you help a new student feel comfortable?"),
    ("Exam Week Balance", "How can students stay calm during a busy exam week?"),
    ("Family Traditions", "Which family tradition would you like to keep forever?"),
    ("Unexpected Weather", "How would heavy rain change your plans for the day?"),
    ("A Better Classroom", "What one change would improve your classroom?"),
    ("Volunteer Day", "How could students help their local community?"),
    ("Language Learning", "What makes learning a new language enjoyable?"),
    ("School Library", "How could your school library become more inviting?"),
    ("Creative Writing", "What kind of story would you enjoy writing?"),
    ("Cafeteria Choices", "What would make school lunch healthier and tastier?"),
    ("Morning Routine", "What helps your morning begin smoothly?"),
    ("Public Transport", "How can a journey across the city be less stressful?"),
    ("Photography Walk", "What would you photograph in your neighbourhood?"),
    ("Cultural Festival", "What could students share at a cultural festival?"),
    ("Time Management", "How do you make time for study and relaxation?"),
    ("Science Curiosity", "Which everyday mystery would you like science to explain?"),
    ("Art and Design", "How can a design make an ordinary object more useful?"),
    ("Debate Club", "What helps people disagree in a respectful way?"),
    ("Outdoor Challenge", "Which outdoor activity would you like to try?"),
    ("Digital Creativity", "What would you enjoy creating with digital tools?"),
    ("Pet Stories", "What can people learn from caring for an animal?"),
    ("Future City", "What should a student-friendly future city include?"),
    ("Personal Goals", "Which goal would make you proud this year?"),
    ("Community Helpers", "Whose work makes your neighbourhood better?"),
    ("Holiday Memories", "Which holiday memory still makes you smile?"),
]

READ_ALOUD_BANK = [
    "Could you explain the homework instructions one more time, please?",
    "I have an idea that might help our group finish the project.",
    "Would you like to sit with us during lunch today?",
    "I need a moment to organize my thoughts before I answer.",
    "Your presentation was clear, interesting, and easy to follow.",
    "Could we compare our notes before the next lesson starts?",
    "I agree with your main point and have another example to share.",
    "Please tell me if you need help with your part of the project.",
    "I enjoyed the story because the main character felt realistic.",
    "Our team stayed calm and tried a different plan after the mistake.",
    "I would like to join the club and learn something new.",
    "Can you recommend a book that is exciting but not too difficult?",
    "The science experiment worked better after we checked every step.",
    "I felt nervous at first, but my classmates were very supportive.",
    "We should choose a meeting time that works for everyone.",
    "This question looks difficult, so I will solve it step by step.",
    "I forgot my notebook, but I wrote the key points on paper.",
    "Could you speak a little more slowly so I can follow?",
    "The school trip was memorable because we explored a new place.",
    "I want to improve my answer by adding a clear reason.",
    "My favorite hobby helps me relax after a busy school day.",
    "We can make the classroom friendlier by listening to each other.",
    "I learned a useful lesson from the mistake I made yesterday.",
    "Would you like to practice the dialogue together after class?",
    "The weather changed suddenly, so we moved our plans indoors.",
    "I prefer working in a small group because everyone can contribute.",
    "This app helps me organize assignments and remember important dates.",
    "I would take a visiting friend to see my favorite part of Hong Kong.",
    "The movie ending surprised me and changed my opinion of the character.",
    "Could I borrow your ruler and return it after the lesson?",
    "I am proud that I asked a question when I felt confused.",
    "Our group needs one more example to make the argument convincing.",
    "I understand your viewpoint, even though my opinion is different.",
    "Let us divide the tasks fairly and check our progress tomorrow.",
    "The teacher's feedback helped me make my writing more precise.",
    "I try to stay calm by taking a slow breath before speaking.",
    "A good friend notices when someone feels left out.",
    "We could reduce waste by bringing reusable bottles to school.",
    "I would love to learn how people live in another country.",
    "This song gives me energy whenever I feel tired.",
    "The new student seemed shy, so I invited her to join us.",
    "I finished my section early and can help edit the final slides.",
    "Could you show me how you reached that answer?",
    "I changed my mind after hearing a stronger piece of evidence.",
    "The discussion became more interesting when everyone shared a view.",
    "I plan to review a little each day instead of rushing.",
    "We missed the bus, but we found another safe way home.",
    "I appreciate how patiently you listened to my explanation.",
    "The museum visit made our history lesson feel more real.",
    "I am ready to share my idea with the rest of the class.",
    "Would it be fairer to let every group member vote?",
    "My family always cooks a special meal for this celebration.",
    "I want a career where I can solve useful problems.",
    "The best part of the weekend was laughing with my cousins.",
    "I can support my opinion with an example from school.",
]
